DROP TABLE USER IF EXISTS ;
CREATE TABLE USER (
      id bigint generated BY DEFAULT AS IDENTITY,
      username VARCHAR(40),
      name VARCHAR(20),
      age INT(3),
      balance DECIMAL(10,2),
      PRIMARY KEY(id))